import type { Metadata } from 'next'
import { Nav } from '@/components/Nav'
import { Footer } from '@/components/Footer'
import { RevealScript } from '@/components/RevealScript'

export const metadata: Metadata = {
  title: 'Terms of Service — Leiko',
  description: 'Terms of Service for the Leiko AI business assistant.',
}

export default function TermsPage() {
  return (
    <>
      <Nav />
      <main className="legal">
        <div className="ctn">
          <div className="legal-header rv">
            <div className="lbl">Terms of Service</div>
            <h1>Terms of Service</h1>
            <p className="legal-meta">
              Effective date: March 9, 2026 · Last updated: March 9, 2026
            </p>
          </div>

          <div className="legal-body rv d1">
            <p>
              These Terms of Service (&ldquo;Terms&rdquo;) constitute a legally binding agreement between you (&ldquo;you&rdquo;, &ldquo;your&rdquo;, or &ldquo;User&rdquo;) and Leiko AI Oy (&ldquo;Leiko&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;), a company registered in Finland. These Terms govern your access to and use of the Leiko mobile application, website, APIs, and all related services (collectively, the &ldquo;Service&rdquo;).
            </p>
            <p>
              By creating an account or using the Service, you represent that you are at least 16 years of age, have the legal capacity to enter into these Terms, and agree to be bound by them. If you are using the Service on behalf of an organization, you represent that you have authority to bind that organization to these Terms.
            </p>

            <h2>1. Service Description</h2>
            <p>Leiko is an AI-powered business operating assistant that provides conversational tools for invoicing, receipt and expense management, task and project management, time tracking, calendar management, email summarization, and customer relationship management. The Service uses artificial intelligence to assist with, not replace, your business decisions and actions.</p>
            <p>The Service is currently in beta. Features, functionality, availability, and pricing are subject to change at any time without prior notice during the beta period. We make no guarantees regarding the continued availability of any specific feature or the Service itself during beta.</p>

            <h2>2. Account Registration and Security</h2>
            <p>To use the Service, you must create an account with accurate and complete information. You are responsible for maintaining the confidentiality of your login credentials and for all activities that occur under your account. You must notify us immediately of any unauthorized use of your account.</p>
            <p>We reserve the right to suspend or terminate accounts that violate these Terms, that are used for fraudulent or illegal purposes, or that remain inactive for more than 12 consecutive months, with prior notice where practicable.</p>

            <h2>3. Your Data and Content</h2>

            <h3>3.1 Ownership</h3>
            <p>You retain all ownership rights to the data, content, and information you provide to or create through the Service (&ldquo;Your Data&rdquo;). This includes business documents, invoices, receipts, task descriptions, customer information, and all other content you input or generate using the Service.</p>

            <h3>3.2 License to Leiko</h3>
            <p>By using the Service, you grant Leiko a worldwide, non-exclusive, royalty-free, sublicensable (solely to our service providers and AI model providers to the extent necessary to provide the Service), transferable license to use, process, store, reproduce, display, and transmit Your Data solely for the purposes of:</p>
            <ul>
              <li>Providing, maintaining, and operating the Service</li>
              <li>Processing your instructions and executing requested actions</li>
              <li>Transmitting data to AI model providers for inference processing</li>
              <li>Generating AI responses, suggestions, and automated outputs</li>
              <li>Improving and developing the Service, including through anonymized and aggregated analysis</li>
              <li>Complying with applicable legal obligations</li>
            </ul>
            <p>This license continues for the duration of your account and terminates when Your Data is deleted, except as required for legal compliance or where data has been irreversibly anonymized.</p>

            <h3>3.3 AI-Generated Content</h3>
            <p>Content generated by the AI assistant, including invoice drafts, email summaries, task suggestions, and other outputs (&ldquo;AI Outputs&rdquo;), is provided as-is. You are solely responsible for reviewing, verifying, and approving all AI Outputs before acting on them or distributing them to third parties. AI Outputs may contain errors, inaccuracies, or omissions. Leiko does not guarantee the accuracy, completeness, legality, or fitness for any particular purpose of any AI Output.</p>
            <p>To the extent permissible by applicable law, you own or have the right to use AI Outputs generated specifically for your account based on your inputs and data. Leiko does not claim ownership of AI Outputs.</p>

            <h3>3.4 Data Processing</h3>
            <p>Our collection, use, and processing of Your Data is governed by our <a href="/privacy">Privacy Policy</a>, which is incorporated by reference into these Terms. By agreeing to these Terms, you also agree to our Privacy Policy.</p>

            <h2>4. Acceptable Use</h2>
            <p>You agree not to use the Service to:</p>
            <ul>
              <li>Violate any applicable law, regulation, or third-party right</li>
              <li>Generate, store, or transmit fraudulent invoices, false financial records, or misleading business documents</li>
              <li>Process personal data of third parties in violation of applicable data protection laws, including GDPR</li>
              <li>Attempt to reverse-engineer, decompile, disassemble, or otherwise derive the source code or underlying algorithms of the Service</li>
              <li>Interfere with or disrupt the Service, its servers, or connected networks</li>
              <li>Access or attempt to access other users&apos; accounts or data</li>
              <li>Use the Service to develop a competing product or service</li>
              <li>Automate access to the Service through bots, scrapers, or similar mechanisms without our prior written consent</li>
              <li>Circumvent, disable, or interfere with security features of the Service</li>
              <li>Use the Service in a manner that could damage, disable, overburden, or impair our infrastructure</li>
            </ul>
            <p>We reserve the right to investigate violations and take appropriate action, including suspending or terminating your account without prior notice.</p>

            <h2>5. Third-Party Integrations</h2>
            <p>The Service allows you to connect third-party services, including Google Calendar and Gmail. By enabling these integrations:</p>
            <ul>
              <li>You authorize Leiko to access, retrieve, process, and, where applicable, create, modify, or delete data in those third-party services on your behalf and in accordance with your instructions</li>
              <li>You represent that you have the necessary rights and authorizations to grant Leiko access to those third-party services and the data contained therein</li>
              <li>You acknowledge that Leiko is not responsible for the availability, accuracy, security, or performance of third-party services</li>
              <li>You acknowledge that third-party services are subject to their own terms of service and privacy policies, which you are responsible for reviewing</li>
            </ul>
            <p>You may revoke integration access at any time through the Service settings. Revocation does not affect data already processed prior to disconnection.</p>

            <h2>6. Invoicing and Financial Features</h2>
            <p>The Service provides tools for creating, sending, and tracking invoices, managing expenses, and tracking time. Important limitations:</p>
            <ul>
              <li>Leiko is not an accounting system, a certified invoicing platform, or a tax advisory service. The Service does not replace professional accounting, legal, or tax advice.</li>
              <li>You are solely responsible for the accuracy, completeness, and legal compliance of all invoices you create and send through the Service, including applicable tax calculations, VAT requirements, and invoicing regulations in your jurisdiction.</li>
              <li>We do not validate the correctness of amounts, tax rates, or regulatory compliance of your invoices. AI-suggested amounts are estimates based on available data and must be verified by you before sending.</li>
              <li>We are not liable for any financial losses, tax penalties, regulatory fines, or business damages resulting from inaccurate or non-compliant invoices generated through the Service.</li>
              <li>Invoice delivery depends on third-party email services and is not guaranteed. You should verify that invoices have been received by your clients.</li>
            </ul>

            <h2>7. Fees and Payment</h2>
            <p>The Service is currently offered free of charge during the beta period. We reserve the right to introduce paid subscription plans, modify pricing, or discontinue the free tier at any time. We will provide at least 30 days&apos; advance notice before any pricing changes take effect.</p>
            <p>If paid plans are introduced, access to certain features may be restricted to paid tiers. Your existing data will not be deleted solely due to a transition to paid plans, and you will be given reasonable time to export your data.</p>

            <h2>8. Intellectual Property</h2>

            <h3>8.1 Leiko&apos;s Property</h3>
            <p>The Service, including its design, interface, source code, algorithms, AI prompts, documentation, trademarks, logos, and all related intellectual property, is owned by Leiko AI Oy or its licensors. Nothing in these Terms grants you any rights to Leiko&apos;s intellectual property beyond the limited right to use the Service as permitted herein.</p>

            <h3>8.2 Feedback</h3>
            <p>If you provide feedback, suggestions, ideas, or recommendations regarding the Service (&ldquo;Feedback&rdquo;), you grant Leiko a perpetual, irrevocable, worldwide, royalty-free, fully sublicensable license to use, modify, incorporate, and commercialize such Feedback without any obligation or compensation to you. You waive any moral rights in such Feedback to the extent permitted by law.</p>

            <h2>9. Disclaimers</h2>
            <p>THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, LEIKO DISCLAIMS ALL WARRANTIES, INCLUDING WITHOUT LIMITATION:</p>
            <ul>
              <li>Any implied warranties of merchantability, fitness for a particular purpose, non-infringement, or accuracy</li>
              <li>Any warranty that the Service will be uninterrupted, error-free, secure, or free of viruses or other harmful components</li>
              <li>Any warranty regarding the accuracy, reliability, or completeness of AI-generated content, suggestions, or outputs</li>
              <li>Any warranty that the Service will meet your specific business requirements or that AI outputs will comply with applicable laws or regulations in your jurisdiction</li>
            </ul>
            <p>AI-generated content is probabilistic in nature and may produce incorrect, misleading, or inappropriate results. You acknowledge that you use AI features at your own risk and are solely responsible for verifying all AI outputs before relying on or distributing them.</p>

            <h2>10. Limitation of Liability</h2>
            <p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:</p>
            <p>(a) Leiko shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation damages for loss of profits, revenue, data, business opportunities, goodwill, or anticipated savings, regardless of the cause of action or the theory of liability (including contract, tort, negligence, strict liability, or otherwise), even if Leiko has been advised of the possibility of such damages.</p>
            <p>(b) Leiko&apos;s total aggregate liability for all claims arising out of or relating to these Terms or the Service shall not exceed the greater of (i) the total amount paid by you to Leiko in the twelve (12) months preceding the claim, or (ii) fifty euros (EUR 50.00).</p>
            <p>(c) Without limiting the foregoing, Leiko shall not be liable for: any errors, inaccuracies, or omissions in AI-generated content; financial losses resulting from reliance on AI suggestions; damages arising from unauthorized access to your account due to your failure to maintain credential security; any actions taken by third-party services connected through integrations; or any loss of data caused by circumstances beyond our reasonable control.</p>
            <p>Nothing in these Terms excludes or limits liability that cannot be excluded or limited under applicable law, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation, or any liability that cannot be excluded under mandatory consumer protection laws.</p>

            <h2>11. Indemnification</h2>
            <p>You agree to indemnify, defend, and hold harmless Leiko, its officers, directors, employees, agents, and affiliates from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorneys&apos; fees) arising out of or related to: (a) your use of the Service; (b) Your Data or any content you provide; (c) your violation of these Terms; (d) your violation of any applicable law or third-party right; (e) invoices you create and send through the Service; or (f) any dispute between you and any third party arising from your use of the Service.</p>

            <h2>12. Termination</h2>
            <p>You may terminate your account at any time by deleting it through the Service settings or by contacting us at hello@leiko.ai. We may terminate or suspend your access to the Service at any time, with or without cause, with or without notice, including if we reasonably believe you have violated these Terms.</p>
            <p>Upon termination: (a) your right to use the Service ceases immediately; (b) we will retain Your Data for 30 days to allow for recovery, after which it will be deleted in accordance with our Privacy Policy and applicable legal retention requirements; (c) provisions of these Terms that by their nature should survive termination shall survive, including Sections 3.2 (License), 8.2 (Feedback), 9 (Disclaimers), 10 (Limitation of Liability), 11 (Indemnification), 13 (Governing Law), and 14 (Dispute Resolution).</p>
            <p>We may discontinue the Service entirely at any time. In such event, we will provide at least 30 days&apos; notice and offer data export functionality so you can retrieve Your Data.</p>

            <h2>13. Governing Law</h2>
            <p>These Terms shall be governed by and construed in accordance with the laws of Finland, without regard to its conflict of law provisions. The application of the United Nations Convention on Contracts for the International Sale of Goods is expressly excluded.</p>
            <p>For consumers in the EU: Nothing in these Terms affects your mandatory rights under the laws of your country of residence where those laws provide a higher level of consumer protection. You may bring proceedings in the courts of your country of residence.</p>

            <h2>14. Dispute Resolution</h2>
            <p>In the event of a dispute arising from or relating to these Terms or the Service, the parties agree to first attempt to resolve the dispute informally by contacting hello@leiko.ai. If the dispute is not resolved within 30 days, either party may initiate formal proceedings.</p>
            <p>For business users: any unresolved dispute shall be submitted to the exclusive jurisdiction of the courts of Helsinki, Finland.</p>
            <p>For consumers in the EU: you may also submit disputes to the Online Dispute Resolution platform at <a href="https://ec.europa.eu/consumers/odr" target="_blank" rel="noopener noreferrer">https://ec.europa.eu/consumers/odr</a> or to your local consumer dispute resolution body.</p>

            <h2>15. Modifications to These Terms</h2>
            <p>We reserve the right to modify these Terms at any time. We will notify you of material changes at least 14 days before the revised Terms take effect, through the Service, by email, or by other appropriate means. Your continued use of the Service after the effective date constitutes acceptance. If you do not agree to the revised Terms, you must stop using the Service and delete your account before the effective date.</p>
            <p>Non-material changes (such as typographical corrections or clarifications that do not alter the substance of the Terms) may take effect immediately upon posting.</p>

            <h2>16. General Provisions</h2>
            <p><strong>Entire Agreement:</strong> These Terms, together with the Privacy Policy and any other policies referenced herein, constitute the entire agreement between you and Leiko regarding the Service, superseding all prior agreements and understandings.</p>
            <p><strong>Severability:</strong> If any provision of these Terms is found to be invalid, illegal, or unenforceable, the remaining provisions shall remain in full force and effect. The invalid provision shall be modified to the minimum extent necessary to make it valid and enforceable.</p>
            <p><strong>Waiver:</strong> Our failure to enforce any right or provision of these Terms shall not constitute a waiver of that right or provision.</p>
            <p><strong>Assignment:</strong> You may not assign or transfer your rights or obligations under these Terms without our prior written consent. We may assign our rights and obligations without restriction, including in connection with a merger, acquisition, or sale of assets.</p>
            <p><strong>Force Majeure:</strong> Leiko shall not be liable for any failure or delay in performance due to circumstances beyond our reasonable control, including natural disasters, war, terrorism, pandemics, government actions, power failures, internet disruptions, or third-party service outages.</p>
            <p><strong>No Agency:</strong> Nothing in these Terms creates any agency, partnership, joint venture, or employment relationship between you and Leiko.</p>
            <p><strong>Notices:</strong> Notices to Leiko must be sent to hello@leiko.ai. We may provide notices to you through the Service, to the email address associated with your account, or by other reasonable means.</p>

            <h2>17. Beta Service Terms</h2>
            <p>The Service is currently in a beta testing phase. By using the beta Service, you acknowledge and agree that:</p>
            <ul>
              <li>The Service may contain bugs, errors, and incomplete features, and is not guaranteed to function as described</li>
              <li>We may collect additional usage data and feedback during the beta period to improve the Service</li>
              <li>Features, APIs, and functionality may change materially without prior notice</li>
              <li>The beta period may end at any time, and access may be modified or terminated without liability</li>
              <li>No service level agreement (SLA) applies during the beta period, including uptime guarantees</li>
              <li>Data created during beta may not be fully preserved in the transition to general availability, though we will make reasonable efforts to maintain data continuity</li>
            </ul>

            <h2>18. Contact Information</h2>
            <ul>
              <li><strong>Entity:</strong> Leiko AI Oy</li>
              <li><strong>Email:</strong> hello@leiko.ai</li>
              <li><strong>Privacy inquiries:</strong> privacy@leiko.ai</li>
              <li><strong>Registered in:</strong> Finland</li>
            </ul>
            <p>These Terms of Service are governed by the laws of Finland and the European Union.</p>
          </div>
        </div>
      </main>
      <Footer />
      <RevealScript />
    </>
  )
}
